export const Constants = {
    FETCH_PEOPLE_REQUEST: 'FETCH_PEOPLE_REQUEST',
    FETCH_PEOPLE_SUCCESS: 'FETCH_PEOPLE_SUCCESS',
    FETCH_NEXT_URL: 'FETCH_NEXT_URL',
    FETCH_PEOPLE_ERROR: 'FETCH_PEOPLE_ERROR',
    FETCH_PEOPLE_URL: 'https://swapi.dev/api/people/'
}
